apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecosia
  name: ecosia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecosia
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecosia
    spec:
      containers:
      - image: ecosia
        name: ecosia
        imagePullPolicy: Never
        resources: {}
        #resources:
        #  limits:
        #    cpu: "1"
        #  requests:
        #    cpu: "0.5"
        ports:
          - containerPort: 80
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: ecosia
  labels:
    app: ecosia
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: ecosia
  type: NodePort
  externalTrafficPolicy: Cluster
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecosia
spec:
  rules:
  - host: local.ecosia.org
    http:
      paths:
      - backend:
          serviceName: ecosia
          servicePort: 80
        path: /
---